# Alpenglow foot theme
# https://codeberg.org/dnkl/foot

[colors]
alpha=0.92
alpha-mode=all

background=121515
foreground=FCFBF8

cursor=121515 FCFBF8
selection-foreground=121515
selection-background=FCFBF8

regular0=121515
regular1=A48364
regular2=F8E7AE
regular3=FEE88B
regular4=6E89C2
regular5=8BA6DF
regular6=59c1c0
regular7=FCFBF8

bright0=697171
bright1=cca87f
bright2=f6e59c
bright3=fce668
bright4=90acf5
bright5=adc9ff
bright6=70e4e3
bright7=e5e4e1
