# Background and foreground colors
background = #121515
foreground = #FCFBF8

background-opacity = 0.92

# Standard colors
palette = 0=#121515
palette = 1=#A48364
palette = 2=#F8E7AE
palette = 3=#FEE88B
palette = 4=#6E89C2
palette = 5=#8BA6DF
palette = 6=#59c1c0
palette = 7=#FCFBF8

# Bright colors
palette = 8=#697171
palette = 9=#cca87f
palette = 10=#f6e59c
palette = 11=#fce668
palette = 12=#90acf5
palette = 13=#adc9ff
palette = 14=#70e4e3
palette = 15=#e5e4e1
