$color = rgba(18, 21, 21, 1)
$inner_color = rgba(18, 21, 21, 0.66)
$outer_color = rgba(139, 166, 223, 1)
$font_color = rgba(252, 251, 248, 1)
$placeholder_color = rgba(252, 251, 248, 0.7)
$check_color = rgba(89, 193, 192, 1)
