background            #121515
foreground            #FCFBF8

background_opacity 0.85

# black
color0  #121515
color8  #697171

# red
color1  #A48364
color9  #cca87f

# green
color2  #F8E7AE
color10 #f6e59c

# yellow
color3  #FEE88B
color11 #fce668

# blue
color4  #6E89C2
color12 #90acf5

# magenta
color5  #8BA6DF
color13 #adc9ff

#cyan
color6  #59c1c0
color14 #70e4e3

#white
color7  #FCFBF8
color15 #e5e4e1


